# ==============================================================================
# Missing Value Semantics (NA vs. NaN vs. NULL)
# ==============================================================================

library(tidyverse)

# NA (Not Available): The "Unknown Value" (Epistemic Missingness) --------------
# NA represents a real-world value that exists in reality, but was not measured.

# (A) NA Propagation: "Unknown + 5 = Unknown"
cat("5 + NA =", 5 + NA, "\n")
cat("NA > 10 =", NA > 10, "\n")

# (B) R computes boolean logic correctly under uncertainty:
cat("TRUE | NA  =", TRUE | NA, "\n")   # TRUE  (Because TRUE or anything is TRUE)
cat("FALSE & NA =", FALSE & NA, "\n")  # FALSE (Because FALSE and anything is FALSE)
cat("TRUE & NA  =", TRUE & NA, "\n")   # NA    (Depends on the unknown value)

# (C) Statistical Aggregation with NA
measurements <- c(10, 25, NA, 40)
mean(measurements)                 # Returns NA (safety feature!)
mean(measurements, na.rm = TRUE)   # Returns 25 (explicitly drops NA)

# NaN (Not a Number): The "Mathematical Impossibility" -------------------------
# NaN is generated by undefined mathematical operations.

val_nan1 <- 0 / 0
val_nan2 <- Inf - Inf
val_nan3 <- sqrt(-1 + 0i) # Complex vs Real: suppressWarnings(sqrt(-1)) yields NaN

cat("0 / 0 yields:", val_nan1, "\n")

# In R, all NaNs are considered missing (NA), but not all NAs are NaNs!
is.nan(NaN)  # TRUE
is.nan(NA)   # FALSE (NA is missing, but not a math error)
is.na(NaN)   # TRUE  (NaN is technically missing data)
is.na(NA)    # TRUE


# NULL: The "Complete Absence" (Zero-Length Object) ----------------------------
# NULL represents nothingness / an empty object. It does NOT occupy memory space.

empty_val <- NULL
length(empty_val)  # 0

# (A) NULL disappears inside vectors:
vec_with_null <- c(1, NULL, 3, NULL, 5)
print(vec_with_null)  # Returns just: 1 3 5 (NULL is completely omitted!)

# (B) NULL is used to delete columns from data frames:
test_df <- tibble(a = 1:3, b = 4:6)
test_df$b <- NULL    # Completely drops column 'b'
print(test_df)

# (C) Testing for NULL:
is.null(empty_val)   # TRUE
is.null(NA)          # FALSE (NA is an actual element of length 1)